Repository GDGVIT/Selenium-Cookie-Injector, pull requests merged in 2020-01, with the labels that each got.

#12 Changed package name
  setup.py
Labels: bug

#16 [WIP] stable release and contributor rules
  CONTRIBUTORS.md
  setup.py
Labels: release

#17 Add a badge for pypi package version
  README.md
Labels: enhancement

#18 Changed imports
  SeleniumCookies/__init__.py
  SeleniumCookies/cookie_injector.py
  SeleniumCookies/tests/tests.py
Labels: bug
